name       : qgit
version    : "2.10"
release    : 2
source     :
    - https://github.com/tibirna/qgit/archive/refs/tags/qgit-2.10.tar.gz : 1fc74fbd25c8ccbee9f7d4a8817b0a82ffa5a3a281b324febe4e90ea7c721153
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Graphical interface for git
description: |
    With qgit you will be able to browse revisions history, view patch content and changed files, graphically following different development branches.
optimize   :
    - lto
builddeps  :
    - pkgconfig(Qt5Gui)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
